### ISSUE TITLE
Symlink Issues - __FILE__ vs. get_theme_root()

### ISSUE THREAD

**Issue by Luehrsen** [Freemius/wordpress-sdk#175]
Short Prefix: This is most likely just a development issue. Our development workflow is based around the theme sitting in a build process folder (build/trunk) in its own repository. To test the theme locally we create Symlinks between the WordPress Theme Folder and the trunk folder.

**Actual Behavior**:
 -  `What is the issue? (*)`
The symlink logic doesn't see that it is sitting in a theme folder. Therefore the SDK ist unable to work for us locally, what makes development very hard. The main issue is at line [47 of the start.php](https://github.com/Freemius/wordpress-sdk/blob/8191da5256d650e5911a218a952eb01fb9986991/start.php#L47) file of the theme SDK. 

As a reference, this is the output of the variables: 
    
    $file_path = "/Projekte/wp_development/themes/agncy/trunk/freemius/start.php";
    $fs_root_path = "/Projekte/wp_development/themes/agncy/trunk/freemius";
    $themes_directory = "/Projekte/htdocs/wpdemo/wp-content/themes";
    $themes_directory_name = "themes";
    $theme_candidate_basename = "trunk/freemius";

This all stems from the fact, that the __FILE__ constant resolves symlinks. This in itself is not a problem, but the checks on Line 55 can't see that the SKD is indeed in a theme folder (just behind a symlink) and so the SDK doesn't work correctly.

 -  `What is the expected behavior?`
I expect the SDK to compare paths in a way that pay respect to potential symlinks. Maybe offer an option or a development constant, that we can set in the wp-config.php to override the automatic pathfinding. 

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.2.7
 -  `WordPress Version:` 4.8.1
 -  `PHP Version:` 7.1.0

**Plugin / Theme**: (*)
 -  `Name:` Agncy
 -  `Slug:` agncy
 -  `Freemius ID:` 1282

**Additional Information**:
 -  `Browser Type: (*)` Chrome 
 -  `Browser Version: (*)`  60.0.3112.90
 -  `OS: (*)` MacOS X / Mamp

**Comment by vovafeldman** [comment]
@Luehrsen just to make sure I have all the data, is your symlink maps `/Projekte/wp_development/themes/agncy/trunk/` to `/Projekte/wp_development/themes/agncy/`?

**Comment by Luehrsen** [comment]
No, the symlink goes into a completely different file tree. 

`/Projekte/wp_development/themes/agncy/trunk` => '/Projekte/htdocs/wpdemo/wp-content/themes/agncy/'

We keep our theme separated from the Wordpress instance for easier development. That way we can test the theme with multiple Wordpress systems and remain in a continuous integration environment.

**Comment by vovafeldman** [comment]
It should work then. Let's schedule a quick TeamViewer session so I can do some vars inspection on right on your environment using a debugger.

**Comment by Luehrsen** [comment]
Can do. Feel free to add me on any IM or Facebook to coordinate that a bit better. 

I'm sitting in GMT+2 (Munich), so for me anything in the afternoon this week should work.

**Comment by Luehrsen** [comment]
As a reference: With a standard drop-in installation, these are the errors I'm getting. 

AFAIK most of these errors fall back to the fact that the script cannot see itself in the theme folder, therefore falls back to plugin mode and breaks. 

![wpdemo local-](https://user-images.githubusercontent.com/1105871/29763923-77e72824-8bd5-11e7-8348-c9e3e2389252.png)

**Comment by Luehrsen** [comment]
What put me on the right path was seeing the crooked enqueue path for the styles: 

![bildschirmfoto 2017-08-28 um 09 45 46](https://user-images.githubusercontent.com/1105871/29764020-d6f8dc18-8bd5-11e7-88b5-3aa982a9e905.png)

**Comment by vovafeldman** [comment]
Sent you a FB friend request.

**Comment by Luehrsen** [comment]
Started working on this again. Installed fresh code from the develop branch at commit bc2bcc809b949cc704fd9e49636f54c5161a1e3e.

This is the xdebug output: 
![wpdemo local-wp-admin- 1](https://user-images.githubusercontent.com/1105871/30475437-257b8cac-9a07-11e7-9ff0-408df24e1d50.png)

**Comment by Luehrsen** [comment]
I have var dumped the result of 'get_module_type()' and my theme self identifies as plugin.

![bildschirmfoto 2017-09-15 um 11 28 19](https://user-images.githubusercontent.com/1105871/30476063-216198a8-9a09-11e7-80f0-04689f35f761.png)

<img width="1006" alt="bildschirmfoto 2017-09-15 um 11 29 15" src="https://user-images.githubusercontent.com/1105871/30476067-264c1492-9a09-11e7-8d49-87ea6065f16a.png">

**Comment by Luehrsen** [comment]
The function ´get_caller_main_file_and_type´also has problems correctly identifying the theme. 

![bildschirmfoto 2017-09-15 um 11 44 07](https://user-images.githubusercontent.com/1105871/30476773-53015b94-9a0b-11e7-8460-8ec751a9f61e.png)

**Comment by Luehrsen** [comment]
I think I traced (one of) the issues to https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L1004

That if statement returns false in my case.

**Comment by Luehrsen** [comment]
My current fix looks like this: 

```
if ( $caller_file_path == fs_normalize_path( realpath( trailingslashit( get_stylesheet_directory() ) . basename( $caller_file_path ) ) ) ) {
         $module_type           = WP_FS__MODULE_TYPE_THEME;
         $caller_file_candidate = $caller_file_path;
         continue;
}
```

The assumption is: If we are talking about a theme and if the caller_file is function.php, it must be in the directory of the current active theme. So I map it like this, solve all symlinks with 'realpath' and we have a match.

Current issues could arise, if the sdk is called from a parent theme.

**Comment by Luehrsen** [comment]
Next symlink issue: 

The function `fs_asset_url` can't construct a functioning URL, so i don't get assets. :D

**Comment by Luehrsen** [comment]
Just as a side note: A lot of these issues would resolve if you could provide URI and PATH to the SDK folder from the init function constructor.

**Comment by vovafeldman** [comment]
@Luehrsen for performance and many additional reasons, the SDK has a special mechanism to automatically identify and use the newest SDK in the website among all the plugins and themes. Also, currently, the constructor of each module is initiated prior to the settings configuration (something that we'll try to change in the future), and since we need the path during the constructor execution, adding the URI and/or PATH won't help.

**Comment by vovafeldman** [comment]
@Luehrsen is the last `fs_asset_url()` issue you mentioned happens in the latest SDK version?

**Comment by Luehrsen** [comment]
Yes, I am on the current master branch. (Tested 3 minutes ago)

![bildschirmfoto 2017-09-27 um 10 20 45](https://user-images.githubusercontent.com/1105871/30902997-9b84dfec-a36d-11e7-8e97-1e27a8aeec11.png)

**Comment by vovafeldman** [comment]
@Luehrsen can you kindly report if the issue happens with the latest `develop` branch? We made a bunch of improvements to symlinks and environment replications that should resolve this issue.

**Comment by Luehrsen** [comment]
@vovafeldman Downloaded 3 Minutes ago. 

I am still getting malformed asset URLs and a new fatal error. 
<img width="1235" alt="bildschirmfoto 2017-11-28 um 14 31 36" src="https://user-images.githubusercontent.com/1105871/33322380-77bff6de-d449-11e7-8368-5cbd4e3727b7.png">

<img width="1248" alt="bildschirmfoto 2017-11-28 um 14 36 13" src="https://user-images.githubusercontent.com/1105871/33322400-8372d276-d449-11e7-8b74-25ed7c3692ed.png">

**Comment by victorholt** [comment]
Hey @vovafeldman I believe this might be related as I'm having a symlink issue as well. The following line:

https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L848

 seems to be returning a non-symlink version of a site I'm working on. I'm using this plugin through the stop-user-enumeration plugin and I was wondering if there were any solutions for resolving this issue through a configuration setting?

**Comment by vovafeldman** [comment]
@Luehrsen please send us a link to the zip file of the theme and we'll test it on our end.

@victorholt did you try to use the `develop` branch?
